### ISSUE TITLE
linkedin link navigate to not found

### ISSUE THREAD

**Issue by tktcorporation** [kawamataryo/kawamataryo#1]
https://github.com/kawamataryo/kawamataryo/blob/5eaa4003822d440cfb6d9e6d6b6844ce9341f9af/README.md?plain=1#L9
I clicked the linkedin link button. but it navigated to github notfound page.
I consider that the href needs `https://`.

**Comment by kawamataryo** [comment]
Thanks for your issue! 👍 
I fixed it.
